# GSM8K (Grade School Math 8K)
# 8.5K grade school math word problems
# Tests mathematical reasoning and arithmetic

model:
  model_name: "meta-llama/Llama-3.1-8B-Instruct"
  model_max_length: 2048
  dtype: "bfloat16"
  attn_implementation: "flash_attention_2"

generation:
  per_device_batch_size: 4
  temperature: 0.0
  max_new_tokens: 512

tasks:
  - backend: "lm_harness"
    task: "gsm8k"
    num_fewshot: 8  # 8-shot evaluation (standard for GSM8K)
    output_path: "./eval_results/gsm8k"
