# Project-scoped KOA configuration for the koa CLI.
# Copy to koa-config.yaml and customise for each repository.

project: <repo_name>

# Optional per-project overrides
# default_partition: kill-shared
# modules:
#   python: lang/Python/3.11.5-GCCcore-13.2.0
#   cuda: system/CUDA/12.2.0

env_watch:
  - scripts/setup_env.sh
  - requirements.txt
  - pyproject.toml
