# Qwen3 4B with LoRA fine-tuning
# Good balance of capability and efficiency
# Excellent for most fine-tuning tasks

model:
  model_name: "Qwen/Qwen3-4B"
  model_max_length: 32768
  dtype: "bfloat16"
  attn_implementation: "flash_attention_2"
  use_cache: false

data:
  train_dataset:
    dataset_name: "yahma/alpaca-cleaned"
    split: "train"
  target_column: "text"
  template: "qwen"

training:
  trainer_type: "sft"
  per_device_train_batch_size: 4
  gradient_accumulation_steps: 16  # Effective batch size: 4 * 16 = 64
  learning_rate: 2.0e-04
  lr_scheduler_type: "cosine"
  warmup_ratio: 0.03
  num_train_epochs: 3
  save_steps: 100
  logging_steps: 10
  save_total_limit: 3
  output_dir: "./output/qwen3_4b_lora"
  bf16: true
  gradient_checkpointing: true
  optim: "adamw_torch_fused"

  # Evaluation
  eval_strategy: "steps"
  eval_steps: 100

  # Logging
  report_to: "none"

peft:
  type: "lora"
  lora_r: 16  # Higher rank for 4B model
  lora_alpha: 32
  lora_dropout: 0.05
  lora_target_modules: ["q_proj", "v_proj", "k_proj", "o_proj", "gate_proj", "up_proj", "down_proj"]
  bias: "none"
  task_type: "CAUSAL_LM"
