# Qwen3-VL 4B with LoRA training on M2SV-SFT dataset
# Vision-Language Model for street-view to map matching task
# Memory efficient: ~20-24GB GPU memory with LoRA

model:
  model_name: "Qwen/Qwen3-VL-4B-Instruct"
  model_max_length: 2048  # Qwen3-VL context length
  dtype: "bfloat16"
  use_cache: false

  # Optional: Enable for even lower memory (QLoRA)
  # load_in_4bit: false
  # bnb_4bit_quant_type: "nf4"
  # bnb_4bit_compute_dtype: "bfloat16"
  # bnb_4bit_use_double_quant: true

data:
  train_dataset:
    dataset_name: "yosubshin/m2sv-sft"
    split: "train"
    # Optional: limit for quick testing
    # limit: 100

training:
  trainer_type: "standard"  # Using HF Trainer for VLM
  per_device_train_batch_size: 2
  gradient_accumulation_steps: 8  # Effective batch size: 2 * 8 = 16
  learning_rate: 2.0e-04
  lr_scheduler_type: "cosine"
  warmup_ratio: 0.03
  max_steps: 3000  # ~4-6 hours of training
  save_steps: 500
  logging_steps: 10
  save_total_limit: 2
  output_dir: "./train/results/local/qwen3_vl_4b_lora_m2sv"
  bf16: true
  gradient_checkpointing: true
  optim: "adamw_torch"

  # Logging - W&B enabled by default
  report_to: "wandb"

peft:
  type: "lora"
  lora_r: 16
  lora_alpha: 32
  lora_dropout: 0.05
  # Target modules for Qwen3-VL vision-language model
  lora_target_modules:
    - "q_proj"
    - "v_proj"
    - "k_proj"
    - "o_proj"
  bias: "none"
