# Baseline evaluation config for Qwen3-VL-4B on M2SV-SFT TEST split
# Use this to measure the out-of-the-box performance before fine-tuning.
#
# USAGE:
#   koa-ml submit eval/scripts/sft_qwen3_4b/eval_base.slurm

model:
  model_name: "Qwen/Qwen3-VL-4B-Instruct"
  dtype: "float16"
  device_map: "auto"

dataset:
  name: "yosubshin/m2sv-sft"
  split: "test"
  fallback_split: "train"

generation:
  max_new_tokens: 128
  temperature: 0.1

  # Optional: Uncomment to run on a subset first
  # limit: 50

inference:
  hf:
    batch_size: 1

output:
  dir: "./eval/results/local/qwen3_4b_base_m2sv"
  save_predictions: true

wandb:
  enabled: true
  tags:
    - "qwen3-4b"
    - "m2sv"
    - "baseline"
  notes: "Baseline evaluation of pretrained Qwen3-VL-4B on M2SV test split"
