# Quick evaluation config for testing
# Uses SmolLM 135M model - fast to evaluate
# Runs subset of MMLU for quick verification

model:
  model_name: "HuggingFaceTB/SmolLM2-135M-Instruct"
  model_max_length: 2048
  dtype: "bfloat16"
  attn_implementation: "sdpa"

generation:
  per_device_batch_size: 8
  temperature: 0.0
  max_new_tokens: 256

tasks:
  # Quick test with a single MMLU subtask
  - backend: "lm_harness"
    task: "mmlu_computer_science"
    num_fewshot: 5
    output_path: "./eval_results/quickstart"
