# Evaluation config for Qwen3-VL on the M2SV dataset

model:
  model_name: "Qwen/Qwen3-VL-4B-Instruct"
  dtype: "float16"
  device_map: "auto"

dataset:
  name: "yosubshin/m2sv"
  split: "train"

generation:
  max_new_tokens: 4096
  temperature: 0.1
  limit:

output:
  dir: "./eval/results/local/qwen3_vl_m2sv"
  save_predictions: true

inference:
  backend: vllm
  vllm:
    max_concurrency: 8
    request_timeout_s: 120
    max_retries: 3
  hf:
    batch_size: 4