# Alpaca Cleaned Dataset Configuration
# High-quality instruction-following dataset
# ~52K instruction-following examples

train_dataset:
  dataset_name: "yahma/alpaca-cleaned"
  split: "train"

# Expected format: instruction, input, output columns
# Uses Alpaca prompt template
target_column: "text"
template: "alpaca"

# Dataset info
description: |
  Alpaca-cleaned is a curated version of the original Alpaca dataset.
  Contains ~52K instruction-following examples covering diverse tasks.
  Quality: High (human-curated cleaning)

# Typical use cases:
# - General instruction following
# - Task generalization
# - Base model training
