# Custom Dataset Configuration Template
# Copy this file and modify for your own dataset

train_dataset:
  dataset_name: "your-username/your-dataset"  # HuggingFace dataset ID
  split: "train"  # Dataset split to use

# If your dataset needs specific column names:
# instruction_column: "question"
# input_column: "context"
# output_column: "answer"

# Or if your dataset is pre-formatted:
target_column: "text"

# Prompt template to use (if not pre-formatted)
# Options: "alpaca", "llama3", "dolly", or custom
template: "alpaca"

# Optional: Validation dataset
# validation_dataset:
#   dataset_name: "your-username/your-dataset"
#   split: "validation"

# Dataset info
description: |
  Add a description of your dataset here.
  Include information about:
  - Size (number of examples)
  - Quality
  - Source
  - Use cases

# Example of loading a local dataset:
# train_dataset:
#   dataset_name: "json"
#   data_files: "./data/train.json"
#   split: "train"
